site_name: Tiefgang Wiki
docs_dir: Wiki
theme:
  name: material
  features:
    - content.tabs.link
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.escapeall:
      hardbreak: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
